name: Talk Desk CI/CD
on:
  push:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./fev_2/Dockerfile
          push: true
          tags: congquyenhuynh111/app3:v1

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: 34.197.192.27
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker stop my-container-name || true
            docker rm my-container-name || true 
            docker pull congquyenhuynh111/app3:v1
            docker run -p 80:80 -d congquyenhuynh111/app3:v1
