name: Talk Desk CI
on:
  push:
    branches: [dev]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: 3.214.182.105
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            if [ -d "Web_TalkDesk" ]; then
            cd Web_TalkDesk
            git pull origin dev
            cd ~
            else
              git clone -b dev https://github.com/LuongXuanThang20110724/Web_TalkDesk.git
            fi
      - name: Run back-end and front-end
        uses: appleboy/ssh-action@master
        with:
          host: 3.214.182.105
          username: ec2-user
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd ~
            cd Web_TalkDesk
            sudo docker-compose down
            sudo docker system prune --all --force --volumes
            sudo docker-compose up -d



