name: Talk Desk CI/CD
on:
  push:
<<<<<<< HEAD
    branches: 
      - main 
jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
          
        - name: Login to Docker Hub
          run: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Build and push Docker image
          uses: docker/build-push-action@v2
          with:
            context: .
            push: true
            tags: congquyenhuynh111/app3:v1
=======
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
>>>>>>> 822fd22df510b8c3953f4efcfdcebb3228f9137e

      - name: Login Docker Hub
        run: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup Docker image build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: congquyenhuynh111/app3:v1

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: 34.197.192.27
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker stop my-container-name || true
            docker rm my-container-name || true 
            docker pull congquyenhuynh111/app3:v1
            docker run -p 80:80 -d congquyenhuynh111/app3:v1
